In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df=pd.read_csv("D:\\Veda Internship\\Sakshi\\Super_Store_DataCleaning\\Task9_Descriptive_Statistics\\Dataset\\Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [8]:
columns = ["Age", "Fare", "SibSp", "Parch", "Pclass"]

In [9]:
print(df[columns].head())

     Age     Fare  SibSp  Parch  Pclass
1   38.0  71.2833      1      0       1
3   35.0  53.1000      1      0       1
6   54.0  51.8625      0      0       1
10   4.0  16.7000      1      1       3
11  58.0  26.5500      0      0       1

In [10]:
print(df[columns].mean())

Age       35.674426
Fare      78.682469
SibSp      0.464481
Parch      0.475410
Pclass     1.191257
dtype: float64

In [11]:
print(df[columns].median())

Age       36.0
Fare      57.0
SibSp      0.0
Parch      0.0
Pclass     1.0
dtype: float64

In [12]:
print(df[columns].mode().iloc[0])

Age       36.00
Fare      26.55
SibSp      0.00
Parch      0.00
Pclass     1.00
Name: 0, dtype: float64

In [13]:
df[columns].std()

Age       15.643866
Fare      76.347843
SibSp      0.644159
Parch      0.754617
Pclass     0.515187
dtype: float64

In [14]:
percentiles = df[columns].quantile([0.25, 0.50, 0.75])
print(percentiles)

       Age  Fare  SibSp  Parch  Pclass
0.25  24.0  29.7    0.0    0.0     1.0
0.50  36.0  57.0    0.0    0.0     1.0
0.75  47.5  90.0    1.0    1.0     1.0

In [15]:
print(df[columns].skew())

Age       0.009676
Fare      2.715883
SibSp     1.443019
Parch     1.519305
Pclass    2.681459
dtype: float64

In [16]:
summary = pd.DataFrame({
    "Mean": df[columns].mean(),
    "Median": df[columns].median(),
    "Mode": df[columns].mode().iloc[0],
    "Std Dev": df[columns].std(),
    "25th Percentile": df[columns].quantile(0.25),
    "50th Percentile": df[columns].quantile(0.50),
    "75th Percentile": df[columns].quantile(0.75),
    "Skewness": df[columns].skew()
})

print(summary)

             Mean  Median   Mode    Std Dev  25th Percentile  50th Percentile  \
Age     35.674426    36.0  36.00  15.643866             24.0             36.0
Fare    78.682469    57.0  26.55  76.347843             29.7             57.0
SibSp    0.464481     0.0   0.00   0.644159              0.0              0.0
Parch    0.475410     0.0   0.00   0.754617              0.0              0.0
Pclass   1.191257     1.0   1.00   0.515187              1.0              1.0

        75th Percentile  Skewness
Age                47.5  0.009676
Fare               90.0  2.715883
SibSp               1.0  1.443019
Parch               1.0  1.519305
Pclass              1.0  2.681459

In [18]:
import os

os.makedirs("Excel", exist_ok=True)

In [20]:
summary.to_excel(
    "Excel/Task9_Descriptive_Statistics.xlsx",
    index=False
)

print("Excel file created successfully!")

Excel file created successfully!

In [21]:
import os

print(os.path.abspath("Excel/Task9_Descriptive_Statistics.xlsx"))

C:\Daaataaa\Excel\Task9_Descriptive_Statistics.xlsx